routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ListController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [ListController::class, 'index']);

// Route::get('/add', [ListController::class, 'create'])->name('list.create');

Route::post('/checkStatus/{checkStatus}', [ListController::class, 'checkStatus'])->name('list.checkStatus');

Route::get('/searching', [ListController::class, 'searching'])->name('list.searching');

Route::resource('list', ListController::class);

app/Models/Todolist.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Todolist extends Model
{
    use HasFactory;

    protected $fillable = ['todo','status','deadline', 'description'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ListController.php
<?php

namespace App\Http\Controllers;

use App\Models\Todolist;
use Illuminate\Http\Request;

class ListController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $todolist = Todolist::get();
        $todolist = Todolist::paginate(5);
        return view('main', compact('todolist'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'todo'=> 'required',
            'deadline'=> 'required',
            'description'=> 'required|max:255',
        ]);
        

        // save data
        Todolist::create([
            'todo' => $request->todo,
            'deadline' => $request->deadline,
            'description' => $request->description,
            'status' => 'In process'
        ]);


        return redirect('/')->with('success', "{$request->todo} was created successfully");

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $list = Todolist::find($id);
        return view('edit', compact('list'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $todolist = Todolist::findOrFail($id);

        // dd($todolist);
        $form_data = $request->validate([
            'todo' => 'required',
            'deadline' => 'required',
            'description'=> 'required|max:255',
        ]);
        
        $todolist->todo = $form_data['todo'];
        $todolist->deadline = $form_data['deadline'];
        $todolist->description = $form_data['description'];
        
        $todolist->save();
        
        return redirect('/')->with('success', "{$todolist->todo} was updated successfully");

    }



    public function checkStatus($id)
    {
        $todolist = Todolist::findOrFail($id);

        $todolist->status = 'Done';
        $todolist->save();

        return redirect()->back();

    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $todolist = Todolist::find($id);
        $todolist->delete();
        return redirect()->back();
    }


    public function searching(Request $request){
        if($request->search){
            $todolist = Todolist::where('todo','like','%'.$request->search.'%')
            ->orWhere('description','like','%'.$request->search.'%')
            ->orWhere('status','like','%'.$request->search.'%')

            ->paginate(5);
            return view('main',compact('todolist'));
        }

        $todolist  =Todolist::paginate(5);
        return view('main',compact('todolist'));
       
    }


}

resources/views/create.blade.php
<!-- header -->
@include('layouts.header')
<!-- header end  -->

<body>

    <!-- nav -->
    @include('layouts.nav')
    <!-- nav end -->

    <div class="row mt-3 ml-5">
        <div class="col">
            <a href="/">
                <button class="btn btn-primary">Back</button>
            </a>
        </div>
        <div class="col">

        </div>
    </div>

    <div class="card mr-5 ml-5 mt-3 shadow p-3 mb-5 bg-white rounded">

        <form class="needs-validation" action="{{route('list.store')}}" method="POST" enctype="multipart/form-data"
            novalidate>
            @csrf

            <div class="container mt-2">

                <div class="row">
                    <div class="col-7">
                        <div class="form-group">
                            <label for="exampleInputPassword1">Todo</label>
                            <input type="text" name="todo" class="form-control" placeholder="Enter todo here..."
                                required>
                            <div class="invalid-feedback">
                                Please insert task.
                            </div>
                        </div>
                    </div>
                    <div class="col-5">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Deadline</label>
                            <input type="date" name="deadline" class="form-control" required>
                            <div class="invalid-feedback">
                                Please give some date.
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <textarea class="form-control" name="description" id="validationCustom03" cols="5 " rows="5"
                            placeholder="Enter description here..." required></textarea>
                        <div class="invalid-feedback">
                            Please give some description.
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-success mt-3">Submit</button>
            </div>

        </form>
    </div>

</body>

</html>

<script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
        'use strict';
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    })();
</script>

resources/views/edit.blade.php
<!-- header -->
@include('layouts.header')
<!-- header end  -->


<body>

    <!-- nav -->
    @include('layouts.nav')
    <!-- nav end -->

    <div class="row mt-3 ml-5">
        <div class="col">
            <a href="/">
                <button class="btn btn-primary">Back</button>
            </a>
        </div>
        <div class="col">

        </div>
    </div>

    <div class="card mr-5 ml-5 mt-3 shadow p-3 mb-5 bg-white rounded">

        <form action="{{route('list.update',[$list->id])}}" method="POST" enctype="multipart/form-data">@csrf
            {{method_field('PUT')}}


            <div class="container mt-2">

                <div class="row">
                    <div class="col-7">
                        <div class="form-group">
                            <label for="exampleInputPassword1">Todo</label>
                            <input type="text" name="todo" class="form-control" value="{{$list->todo}}"
                                placeholder="Enter todo here..." required>
                            <div class="invalid-feedback">
                                Please insert task.
                            </div>
                        </div>
                    </div>
                    <div class="col-5">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Deadline</label>
                            <input type="date" name="deadline" class="form-control" value="{{$list->deadline}}"
                                placeholder="Enter date" required>
                            <div class="invalid-feedback">
                                Please give some date.
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <textarea class="form-control" name="description" id="validationCustom03" cols="5 " rows="5"
                            placeholder="Enter description here..." required>{{$list->description}}</textarea>
                        <div class="invalid-feedback">
                            Please give some description.
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-success mt-3">Submit</button>
            </div>

        </form>
    </div>
</body>

</html>

resources/views/layouts/fotter.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        </div>
    </div>
</footer>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{{asset('admin/img/logo/logo.png')}}" rel="icon">
    <title>TodoList - Dashboard</title>

</head>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand ml-2" href="/">Laravel Todolist</a>
</nav>

resources/views/main.blade.php
<!-- header -->
@include('layouts.header')
<!-- header end -->

<style>
    #action_button {
        display: grid;
        justify-content: center;
        align-content: center;

        gap: 4px;
        grid-auto-flow: column;
    }
</style>


<body class="bg-light" id="page-top">

    <div id="wrapper">

        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">

                <!-- TopBar -->
                <nav class="navbar navbar-dark bg-dark">
                    <a class="navbar-brand ml-2" href="/">Laravel Todolist</a>
                    <a href="{{route('list.create')}}">
                        <button class="btn btn-primary">Add Now</button>
                    </a>
                </nav>
                <!-- Topbar -->


                <!-- Container Fluid-->

                @if( session('success'))
                <div class="row mt-2">
                    <div class="col-7">

                    </div>
                    <div class="col-5">
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ session('success') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </div>
                </div>
                @endif

                
                <div class="card mr-5 ml-5 mt-3 shadow p-3 mb-3 bg-white rounded">

                    <form action="{{route('list.searching')}}" method="GET">

                        <div class="row mt-3 mb-3">
                            <div class="col-sm ml-5 mt-2">
                                <h3><strong>Todolist</strong></h3>
                            </div>
                            <div class="col-sm-4 mr-3 ">
                                <div class="input-group">
                                    <input type="text" name="search" class="form-control rounded" placeholder="Search"
                                        aria-label="Search" aria-describedby="search-addon" />
                                    <button type="submitsubmit" class="btn btn-outline-primary">Search</button>
                                    <a href="/">
                                        <button class="btn btn-primary ml-1">Reset</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="table-responsive-sm">
                        <table class="table table-striped">
                            <thead>
                                <tr class="text-center">
                                    <th scope="col">No</th>
                                    <th scope="col">To Do</th>
                                    <th scope="col">Deadline</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>


                                </tr>
                            </thead>
                            <tbody>
                                @if(count($todolist)>0)
                                @foreach($todolist as $key => $list)

                                <tr>
                                    <th class="text-center" scope="row"> {{ $todolist->firstItem() + $key }}</th>
                                    <td>
                                        <strong>{{$list->todo}}</strong><br>
                                        <p>{{$list->description}}</p>
                                    </td>
                                    <td class="text-center">
                                        <span class="badge badge-pill badge-secondary">
                                            <?php
                                        $d=strtotime($list->deadline);
                                        echo date("d-m-Y", $d);
                                        ?>
                                        </span>
                                    </td>
                                    <td class="text-center">
                                        @if( $list->status == "In process")
                                        <span class="badge badge-pill badge-info">In process</span>
                                        @else
                                        <span class="badge badge-pill badge-success">Done</span>
                                        @endif
                                    </td>
                                    <td>

                                        <div class="row" id="action_button">

                                            @if( $list->status != "Done")
                                            <form action="{{route('list.checkStatus',[$list->id])}}" method="POST"
                                                onsubmit="return confirmDone()">@csrf
                                                <button type="submit" class="bi bi-check2 btn btn-success"></button>
                                            </form>

                                            <a href="{{route('list.edit',[$list->id])}}">
                                                <button class="bi bi-pencil btn btn-info"></button>
                                            </a>

                                            <form action="{{route('list.destroy',[$list->id])}}" method="POST"
                                                onsubmit="return confirmDelete()">@csrf
                                                {{method_field('DELETE')}}
                                                <button type="submit" class="bi bi-trash btn btn-danger"></button>
                                            </form>

                                            @else
                                            <form action="{{route('list.destroy',[$list->id])}}" method="POST"
                                                onsubmit="return confirmDelete()">@csrf
                                                {{method_field('DELETE')}}
                                                <button type="submit" class="bi bi-trash btn btn-danger"></button>
                                            </form>
                                            @endif

                                        </div>

                                    </td>

                                </tr>
                                @endforeach
                                @else
                                <td class="text-center" colspan="5">There are no task</td>
                                @endif
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-10"></div>
                    <div class="col-sm-2">
                        {{$todolist->links()}}
                    </div>
                </div>


                <br><br>
                <br><br>
                <br><br>

                <!---Container Fluid-->


                <!-- Footer -->
                @include('layouts.fotter')
                <!-- Footer -->

            </div>
        </div>

        <script>
            function confirmDelete() {
                return confirm('Are you sure you want to delete?');
            }

            function confirmDone() {
                return confirm('Are you sure you want to finish this task?');
            }
        </script>

resources/views/todolist/index.blade.php
@extends('layouts.index')

@section('content')

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>


 @endsection